
'use client'
import {useState} from 'react'
type Post={id:number;caption:string;platforms:string[];when:string;status:string;media?:string}
export default function Home(){
 const [view,setView]=useState<'create'|'upcoming'|'accounts'>('create'); const [caption,setCaption]=useState(''); const [platforms,setPlatforms]=useState<string[]>(['Instagram','Facebook']); const [when,setWhen]=useState('now'); const [date,setDate]=useState(''); const [time,setTime]=useState(''); const [media,setMedia]=useState<string>(); const [posts,setPosts]=useState<Post[]>([]); const [calendar,setCalendar]=useState(false)
 const toggle=(p:string)=>setPlatforms(x=>x.includes(p)?x.filter(v=>v!==p):[...x,p])
 const connect=(path:string)=>{window.location.href=path}
 const submit=()=>{if(!caption.trim()&&!media)return;const whenText=when==='now'?'Publishing now':`${date} • ${time}`;setPosts(x=>[{id:Date.now(),caption:caption||'Media post',platforms,when:whenText,status:when==='now'?'Publishing':'Scheduled',media},...x]);setCaption('');setMedia(undefined);setView('upcoming')}
 return <div className="shell"><aside className="side"><div className="brand">Nela<span>Post</span></div><nav className="nav"><button className={view==='create'?'active':''} onClick={()=>setView('create')}>+ Create post</button><button className={view==='upcoming'?'active':''} onClick={()=>setView('upcoming')}>Upcoming</button><button className={view==='accounts'?'active':''} onClick={()=>setView('accounts')}>Accounts</button></nav></aside><main className="main"><div className="top"><div><h1>{view==='create'?'Create post':view==='accounts'?'Accounts':'Upcoming'}</h1><div className="muted">Create. Schedule. Publish.</div></div></div>
 {view==='accounts'?<section className="card"><label className="label">CONNECTED SERVICES</label><div className="account"><div><strong>Google Calendar</strong><div className="muted">Link your calendar to plan scheduled posts.</div></div><button className="secondary" onClick={()=>connect('/api/auth/google')}>{calendar?'Connected':'Connect Google Calendar'}</button></div><div className="account"><div><strong>Instagram + Facebook</strong><div className="muted">NelaPost will ask Meta for permission to publish on your behalf.</div></div><button className="secondary" onClick={()=>connect('/api/auth/meta')}>Connect & grant publishing permission</button></div><div className="notice"><strong>Permission control</strong><br/>The social network's own consent screen appears before access is granted. NelaPost requests publishing permission rather than silently taking access.</div></section>
 :view==='create'?<div className="grid"><section className="card"><label className="label">MEDIA</label><div className="drop">{media?<><div>Media selected</div><img className="preview" src={media}/></>:<><div className="muted">Upload an image or video</div><br/><label className="upload">Choose media<input type="file" accept="image/*,video/*" onChange={e=>{const f=e.target.files?.[0];if(f)setMedia(URL.createObjectURL(f))}}/></label></>}</div><label className="label">CAPTION</label><textarea className="textarea" value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Write your caption..."/><label className="label">POST TO</label><div className="platforms">{['Instagram','Facebook'].map(p=><button key={p} className={'platform '+(platforms.includes(p)?'sel':'')} onClick={()=>toggle(p)}>{platforms.includes(p)?'✓ ':''}{p}</button>)}</div></section><section className="card"><label className="label">WHEN</label><div className="platforms"><button className={'platform '+(when==='now'?'sel':'')} onClick={()=>setWhen('now')}>Post now</button><button className={'platform '+(when==='schedule'?'sel':'')} onClick={()=>setWhen('schedule')}>Schedule</button></div>{when==='schedule'&&<><label className="label">DATE</label><input className="input" type="date" value={date} onChange={e=>setDate(e.target.value)}/><label className="label">TIME</label><input className="input" type="time" value={time} onChange={e=>setTime(e.target.value)}/><button className="calendarLink" onClick={()=>connect('/api/auth/google')}>{calendar?'Google Calendar connected':'Link Google Calendar'}</button></>}<div style={{marginTop:28}}><button className="primary" onClick={submit}>{when==='now'?'Publish now':'Schedule post'}</button></div></section></div>
 :<section className="card">{posts.length?posts.map(p=><div className="post" key={p.id}><div><strong>{p.caption}</strong><div className="muted">{p.when} · {p.platforms.join(' + ')}</div></div><div><span className="pill">{p.status}</span> <button className="secondary" onClick={()=>setPosts(x=>x.filter(q=>q.id!==p.id))}>Delete</button></div></div>):<div className="empty">No upcoming posts yet.</div>}</section>}</main></div>}